name: "nix-flake"
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
    - uses: cachix/cachix-action@v10
      with:
        name: jupyterwith
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - run: |
        cd example/flake
        BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
        echo $BRANCH_NAME
        nix flake lock --override-input jupyterWith ../..
        nix -Lv develop . --command echo OK
